[package]
name = "pygjson"
version = "0.0.10"
edition = "2021"

[lib]
name = "_pygjson"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module", "abi3-py310", "generate-import-lib"] }
gjson = { git = "https://github.com/minefuto/gjson.rs", rev="ea7065a77a41018be8ffc3f014653b9621a67b83" }

[profile.release]
lto = "fat"
codegen-units = 1
